### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by herodrigues** [TyrealGray/MakeItSlow#1]
Hi @TyrealGray 

Nice work on this repository. 
I want to know if you have plans of updating the dependencies of this project.

I'm planning of modifying this app to use it as part of another electron app.

**Comment by TyrealGray** [comment]
Glad to hear this app is helpful. I am using this for my side project, so I might be also updating the dependencies. But you are feel to do anything with this project, also it will be nice if you find something out of date and make a PR or just let me know which one needs to update : )
